package schema;

// Generated Jul 13, 2012 6:22:22 AM by Hibernate Tools 3.4.0.CR1

/**
 * Article generated by hbm2java
 */
public class Article implements java.io.Serializable {

	private int id;
	private String articleId;
	private String title;
	private String volume;
	private String number;
	private String ee;
	private Integer year;
	private String journal;
	private String pages;
	private String month;
	private String cdrom;
	private String url;
	private String publisher;
	private String crossref;
	private String booktitle;
	private String cite;
	private String note;

	public Article() {
	}

	public Article(int id, String articleId) {
		this.id = id;
		this.articleId = articleId;
	}

	public Article(int id, String articleId, String title, String volume,
			String number, String ee, Integer year, String journal,
			String pages, String month, String cdrom, String url,
			String publisher, String crossref, String booktitle, String cite,
			String note) {
		this.id = id;
		this.articleId = articleId;
		this.title = title;
		this.volume = volume;
		this.number = number;
		this.ee = ee;
		this.year = year;
		this.journal = journal;
		this.pages = pages;
		this.month = month;
		this.cdrom = cdrom;
		this.url = url;
		this.publisher = publisher;
		this.crossref = crossref;
		this.booktitle = booktitle;
		this.cite = cite;
		this.note = note;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getArticleId() {
		return this.articleId;
	}

	public void setArticleId(String articleId) {
		this.articleId = articleId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getVolume() {
		return this.volume;
	}

	public void setVolume(String volume) {
		this.volume = volume;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public String getEe() {
		return this.ee;
	}

	public void setEe(String ee) {
		this.ee = ee;
	}

	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	public String getJournal() {
		return this.journal;
	}

	public void setJournal(String journal) {
		this.journal = journal;
	}

	public String getPages() {
		return this.pages;
	}

	public void setPages(String pages) {
		this.pages = pages;
	}

	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	public String getCdrom() {
		return this.cdrom;
	}

	public void setCdrom(String cdrom) {
		this.cdrom = cdrom;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getPublisher() {
		return this.publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	public String getCrossref() {
		return this.crossref;
	}

	public void setCrossref(String crossref) {
		this.crossref = crossref;
	}

	public String getBooktitle() {
		return this.booktitle;
	}

	public void setBooktitle(String booktitle) {
		this.booktitle = booktitle;
	}

	public String getCite() {
		return this.cite;
	}

	public void setCite(String cite) {
		this.cite = cite;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
