package schema;

// Generated Jul 13, 2012 6:22:22 AM by Hibernate Tools 3.4.0.CR1

/**
 * AuthorB generated by hbm2java
 */
public class AuthorB implements java.io.Serializable {

	private AuthorBId id;

	public AuthorB() {
	}

	public AuthorB(AuthorBId id) {
		this.id = id;
	}

	public AuthorBId getId() {
		return this.id;
	}

	public void setId(AuthorBId id) {
		this.id = id;
	}

}
