package schema;

// Generated Jul 13, 2012 6:22:22 AM by Hibernate Tools 3.4.0.CR1

/**
 * AuthorBId generated by hbm2java
 */
public class AuthorBId implements java.io.Serializable {

	private int personId;
	private int bookId;

	public AuthorBId() {
	}

	public AuthorBId(int personId, int bookId) {
		this.personId = personId;
		this.bookId = bookId;
	}

	public int getPersonId() {
		return this.personId;
	}

	public void setPersonId(int personId) {
		this.personId = personId;
	}

	public int getBookId() {
		return this.bookId;
	}

	public void setBookId(int bookId) {
		this.bookId = bookId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AuthorBId))
			return false;
		AuthorBId castOther = (AuthorBId) other;

		return (this.getPersonId() == castOther.getPersonId())
				&& (this.getBookId() == castOther.getBookId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPersonId();
		result = 37 * result + this.getBookId();
		return result;
	}

}
