package schema;

// Generated Jul 13, 2012 6:22:22 AM by Hibernate Tools 3.4.0.CR1

/**
 * AuthorA generated by hbm2java
 */
public class AuthorA implements java.io.Serializable {

	private AuthorAId id;

	public AuthorA() {
	}

	public AuthorA(AuthorAId id) {
		this.id = id;
	}

	public AuthorAId getId() {
		return this.id;
	}

	public void setId(AuthorAId id) {
		this.id = id;
	}

}
