package schema;

// Generated Jul 13, 2012 6:22:22 AM by Hibernate Tools 3.4.0.CR1

/**
 * AuthorWId generated by hbm2java
 */
public class AuthorWId implements java.io.Serializable {

	private int personId;
	private int wwwId;

	public AuthorWId() {
	}

	public AuthorWId(int personId, int wwwId) {
		this.personId = personId;
		this.wwwId = wwwId;
	}

	public int getPersonId() {
		return this.personId;
	}

	public void setPersonId(int personId) {
		this.personId = personId;
	}

	public int getWwwId() {
		return this.wwwId;
	}

	public void setWwwId(int wwwId) {
		this.wwwId = wwwId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AuthorWId))
			return false;
		AuthorWId castOther = (AuthorWId) other;

		return (this.getPersonId() == castOther.getPersonId())
				&& (this.getWwwId() == castOther.getWwwId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPersonId();
		result = 37 * result + this.getWwwId();
		return result;
	}

}
