package schema;

// Generated Jul 13, 2012 6:22:22 AM by Hibernate Tools 3.4.0.CR1

/**
 * AuthorAId generated by hbm2java
 */
public class AuthorAId implements java.io.Serializable {

	private int personId;
	private int articleId;

	public AuthorAId() {
	}

	public AuthorAId(int personId, int articleId) {
		this.personId = personId;
		this.articleId = articleId;
	}

	public int getPersonId() {
		return this.personId;
	}

	public void setPersonId(int personId) {
		this.personId = personId;
	}

	public int getArticleId() {
		return this.articleId;
	}

	public void setArticleId(int articleId) {
		this.articleId = articleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AuthorAId))
			return false;
		AuthorAId castOther = (AuthorAId) other;

		return (this.getPersonId() == castOther.getPersonId())
				&& (this.getArticleId() == castOther.getArticleId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPersonId();
		result = 37 * result + this.getArticleId();
		return result;
	}

}
