package schema;

// Generated Jul 13, 2012 6:22:22 AM by Hibernate Tools 3.4.0.CR1

/**
 * AuthorCId generated by hbm2java
 */
public class AuthorCId implements java.io.Serializable {

	private int personId;
	private int inCollId;

	public AuthorCId() {
	}

	public AuthorCId(int personId, int inCollId) {
		this.personId = personId;
		this.inCollId = inCollId;
	}

	public int getPersonId() {
		return this.personId;
	}

	public void setPersonId(int personId) {
		this.personId = personId;
	}

	public int getInCollId() {
		return this.inCollId;
	}

	public void setInCollId(int inCollId) {
		this.inCollId = inCollId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AuthorCId))
			return false;
		AuthorCId castOther = (AuthorCId) other;

		return (this.getPersonId() == castOther.getPersonId())
				&& (this.getInCollId() == castOther.getInCollId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPersonId();
		result = 37 * result + this.getInCollId();
		return result;
	}

}
