package schema;

// Generated Jul 13, 2012 6:22:22 AM by Hibernate Tools 3.4.0.CR1

/**
 * AuthorI generated by hbm2java
 */
public class AuthorI implements java.io.Serializable {

	private AuthorIId id;

	public AuthorI() {
	}

	public AuthorI(AuthorIId id) {
		this.id = id;
	}

	public AuthorIId getId() {
		return this.id;
	}

	public void setId(AuthorIId id) {
		this.id = id;
	}

}
