package schema;

// Generated Jul 13, 2012 6:22:22 AM by Hibernate Tools 3.4.0.CR1

/**
 * AuthorW generated by hbm2java
 */
public class AuthorW implements java.io.Serializable {

	private AuthorWId id;

	public AuthorW() {
	}

	public AuthorW(AuthorWId id) {
		this.id = id;
	}

	public AuthorWId getId() {
		return this.id;
	}

	public void setId(AuthorWId id) {
		this.id = id;
	}

}
