package schema;

// Generated Jul 13, 2012 6:22:22 AM by Hibernate Tools 3.4.0.CR1

/**
 * AuthorC generated by hbm2java
 */
public class AuthorC implements java.io.Serializable {

	private AuthorCId id;

	public AuthorC() {
	}

	public AuthorC(AuthorCId id) {
		this.id = id;
	}

	public AuthorCId getId() {
		return this.id;
	}

	public void setId(AuthorCId id) {
		this.id = id;
	}

}
