package schema;

// Generated Jul 13, 2012 6:22:22 AM by Hibernate Tools 3.4.0.CR1

/**
 * EditorP generated by hbm2java
 */
public class EditorP implements java.io.Serializable {

	private EditorPId id;

	public EditorP() {
	}

	public EditorP(EditorPId id) {
		this.id = id;
	}

	public EditorPId getId() {
		return this.id;
	}

	public void setId(EditorPId id) {
		this.id = id;
	}

}
