package schema;

// Generated Jul 13, 2012 6:22:22 AM by Hibernate Tools 3.4.0.CR1

/**
 * EditorPId generated by hbm2java
 */
public class EditorPId implements java.io.Serializable {

	private int personId;
	private int procId;

	public EditorPId() {
	}

	public EditorPId(int personId, int procId) {
		this.personId = personId;
		this.procId = procId;
	}

	public int getPersonId() {
		return this.personId;
	}

	public void setPersonId(int personId) {
		this.personId = personId;
	}

	public int getProcId() {
		return this.procId;
	}

	public void setProcId(int procId) {
		this.procId = procId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EditorPId))
			return false;
		EditorPId castOther = (EditorPId) other;

		return (this.getPersonId() == castOther.getPersonId())
				&& (this.getProcId() == castOther.getProcId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPersonId();
		result = 37 * result + this.getProcId();
		return result;
	}

}
