package schema;

// Generated Jul 13, 2012 6:22:22 AM by Hibernate Tools 3.4.0.CR1

/**
 * InCollection generated by hbm2java
 */
public class InCollection implements java.io.Serializable {

	private int id;
	private String inCollId;
	private String title;
	private String ee;
	private Integer year;
	private String pages;
	private String url;
	private String publisher;
	private String crossref;
	private String booktitle;
	private String cite;
	private Integer chapter;
	private String cdrom;
	private String isbn;

	public InCollection() {
	}

	public InCollection(int id, String inCollId) {
		this.id = id;
		this.inCollId = inCollId;
	}

	public InCollection(int id, String inCollId, String title, String ee,
			Integer year, String pages, String url, String publisher,
			String crossref, String booktitle, String cite, Integer chapter,
			String cdrom, String isbn) {
		this.id = id;
		this.inCollId = inCollId;
		this.title = title;
		this.ee = ee;
		this.year = year;
		this.pages = pages;
		this.url = url;
		this.publisher = publisher;
		this.crossref = crossref;
		this.booktitle = booktitle;
		this.cite = cite;
		this.chapter = chapter;
		this.cdrom = cdrom;
		this.isbn = isbn;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getInCollId() {
		return this.inCollId;
	}

	public void setInCollId(String inCollId) {
		this.inCollId = inCollId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getEe() {
		return this.ee;
	}

	public void setEe(String ee) {
		this.ee = ee;
	}

	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	public String getPages() {
		return this.pages;
	}

	public void setPages(String pages) {
		this.pages = pages;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getPublisher() {
		return this.publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	public String getCrossref() {
		return this.crossref;
	}

	public void setCrossref(String crossref) {
		this.crossref = crossref;
	}

	public String getBooktitle() {
		return this.booktitle;
	}

	public void setBooktitle(String booktitle) {
		this.booktitle = booktitle;
	}

	public String getCite() {
		return this.cite;
	}

	public void setCite(String cite) {
		this.cite = cite;
	}

	public Integer getChapter() {
		return this.chapter;
	}

	public void setChapter(Integer chapter) {
		this.chapter = chapter;
	}

	public String getCdrom() {
		return this.cdrom;
	}

	public void setCdrom(String cdrom) {
		this.cdrom = cdrom;
	}

	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

}
