package schema;

// Generated Jul 13, 2012 6:22:22 AM by Hibernate Tools 3.4.0.CR1

/**
 * InProceeding generated by hbm2java
 */
public class InProceeding implements java.io.Serializable {

	private int id;
	private String inProcId;
	private String title;
	private String number;
	private String ee;
	private Integer year;
	private String pages;
	private String url;
	private String crossref;
	private String booktitle;
	private String cite;
	private String note;
	private String month;
	private String cdrom;

	public InProceeding() {
	}

	public InProceeding(int id, String inProcId) {
		this.id = id;
		this.inProcId = inProcId;
	}

	public InProceeding(int id, String inProcId, String title, String number,
			String ee, Integer year, String pages, String url, String crossref,
			String booktitle, String cite, String note, String month,
			String cdrom) {
		this.id = id;
		this.inProcId = inProcId;
		this.title = title;
		this.number = number;
		this.ee = ee;
		this.year = year;
		this.pages = pages;
		this.url = url;
		this.crossref = crossref;
		this.booktitle = booktitle;
		this.cite = cite;
		this.note = note;
		this.month = month;
		this.cdrom = cdrom;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getInProcId() {
		return this.inProcId;
	}

	public void setInProcId(String inProcId) {
		this.inProcId = inProcId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public String getEe() {
		return this.ee;
	}

	public void setEe(String ee) {
		this.ee = ee;
	}

	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	public String getPages() {
		return this.pages;
	}

	public void setPages(String pages) {
		this.pages = pages;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getCrossref() {
		return this.crossref;
	}

	public void setCrossref(String crossref) {
		this.crossref = crossref;
	}

	public String getBooktitle() {
		return this.booktitle;
	}

	public void setBooktitle(String booktitle) {
		this.booktitle = booktitle;
	}

	public String getCite() {
		return this.cite;
	}

	public void setCite(String cite) {
		this.cite = cite;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	public String getCdrom() {
		return this.cdrom;
	}

	public void setCdrom(String cdrom) {
		this.cdrom = cdrom;
	}

}
