package schema;

// Generated Jul 13, 2012 6:22:22 AM by Hibernate Tools 3.4.0.CR1

/**
 * MasterThesis generated by hbm2java
 */
public class MasterThesis implements java.io.Serializable {

	private int id;
	private String thesisId;
	private String title;
	private String ee;
	private Integer year;
	private String url;
	private Integer authorId;

	public MasterThesis() {
	}

	public MasterThesis(int id, String thesisId) {
		this.id = id;
		this.thesisId = thesisId;
	}

	public MasterThesis(int id, String thesisId, String title, String ee,
			Integer year, String url, Integer authorId) {
		this.id = id;
		this.thesisId = thesisId;
		this.title = title;
		this.ee = ee;
		this.year = year;
		this.url = url;
		this.authorId = authorId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getThesisId() {
		return this.thesisId;
	}

	public void setThesisId(String thesisId) {
		this.thesisId = thesisId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getEe() {
		return this.ee;
	}

	public void setEe(String ee) {
		this.ee = ee;
	}

	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Integer getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(Integer authorId) {
		this.authorId = authorId;
	}

}
