package schema;

// Generated Jul 13, 2012 6:22:22 AM by Hibernate Tools 3.4.0.CR1

/**
 * Person generated by hbm2java
 */
public class Person implements java.io.Serializable {

	private int id;
	private String name;
	private String phone;
	private String email;
	private String homepage;
	private String affiliation;
	private String address;
	private String bio;
	private String position;
	private String phdUniv;
	private String phdMajor;
	private String phdDate;
	private String msUniv;
	private String msMajor;
	private String msDate;
	private String bsUniv;
	private String bsMajor;
	private String bsDate;

	public Person() {
	}

	public Person(int id) {
		this.id = id;
	}

	public Person(int id, String name, String phone, String email,
			String homepage, String affiliation, String address, String bio,
			String position, String phdUniv, String phdMajor, String phdDate,
			String msUniv, String msMajor, String msDate, String bsUniv,
			String bsMajor, String bsDate) {
		this.id = id;
		this.name = name;
		this.phone = phone;
		this.email = email;
		this.homepage = homepage;
		this.affiliation = affiliation;
		this.address = address;
		this.bio = bio;
		this.position = position;
		this.phdUniv = phdUniv;
		this.phdMajor = phdMajor;
		this.phdDate = phdDate;
		this.msUniv = msUniv;
		this.msMajor = msMajor;
		this.msDate = msDate;
		this.bsUniv = bsUniv;
		this.bsMajor = bsMajor;
		this.bsDate = bsDate;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getHomepage() {
		return this.homepage;
	}

	public void setHomepage(String homepage) {
		this.homepage = homepage;
	}

	public String getAffiliation() {
		return this.affiliation;
	}

	public void setAffiliation(String affiliation) {
		this.affiliation = affiliation;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getBio() {
		return this.bio;
	}

	public void setBio(String bio) {
		this.bio = bio;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public String getPhdUniv() {
		return this.phdUniv;
	}

	public void setPhdUniv(String phdUniv) {
		this.phdUniv = phdUniv;
	}

	public String getPhdMajor() {
		return this.phdMajor;
	}

	public void setPhdMajor(String phdMajor) {
		this.phdMajor = phdMajor;
	}

	public String getPhdDate() {
		return this.phdDate;
	}

	public void setPhdDate(String phdDate) {
		this.phdDate = phdDate;
	}

	public String getMsUniv() {
		return this.msUniv;
	}

	public void setMsUniv(String msUniv) {
		this.msUniv = msUniv;
	}

	public String getMsMajor() {
		return this.msMajor;
	}

	public void setMsMajor(String msMajor) {
		this.msMajor = msMajor;
	}

	public String getMsDate() {
		return this.msDate;
	}

	public void setMsDate(String msDate) {
		this.msDate = msDate;
	}

	public String getBsUniv() {
		return this.bsUniv;
	}

	public void setBsUniv(String bsUniv) {
		this.bsUniv = bsUniv;
	}

	public String getBsMajor() {
		return this.bsMajor;
	}

	public void setBsMajor(String bsMajor) {
		this.bsMajor = bsMajor;
	}

	public String getBsDate() {
		return this.bsDate;
	}

	public void setBsDate(String bsDate) {
		this.bsDate = bsDate;
	}

}
