package schema;

// Generated Jul 13, 2012 6:22:22 AM by Hibernate Tools 3.4.0.CR1

/**
 * Www generated by hbm2java
 */
public class Www implements java.io.Serializable {

	private int id;
	private String wwwId;
	private String title;
	private String ee;
	private Integer year;
	private String url;
	private String crossref;
	private String booktitle;
	private String cite;
	private String note;

	public Www() {
	}

	public Www(int id, String wwwId) {
		this.id = id;
		this.wwwId = wwwId;
	}

	public Www(int id, String wwwId, String title, String ee, Integer year,
			String url, String crossref, String booktitle, String cite,
			String note) {
		this.id = id;
		this.wwwId = wwwId;
		this.title = title;
		this.ee = ee;
		this.year = year;
		this.url = url;
		this.crossref = crossref;
		this.booktitle = booktitle;
		this.cite = cite;
		this.note = note;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getWwwId() {
		return this.wwwId;
	}

	public void setWwwId(String wwwId) {
		this.wwwId = wwwId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getEe() {
		return this.ee;
	}

	public void setEe(String ee) {
		this.ee = ee;
	}

	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getCrossref() {
		return this.crossref;
	}

	public void setCrossref(String crossref) {
		this.crossref = crossref;
	}

	public String getBooktitle() {
		return this.booktitle;
	}

	public void setBooktitle(String booktitle) {
		this.booktitle = booktitle;
	}

	public String getCite() {
		return this.cite;
	}

	public void setCite(String cite) {
		this.cite = cite;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
